[package]
name = "error_handling"
version = "0.1.0"
edition = "2021"

# 'abort' means to not clean up the stack when panicing
[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
